type: code
visible: false
score: 30
code:
  - .laborantum/src/models/Convolutional/sequential.py
  - .laborantum/texts/course/4. Convolutional NNs/1. Classification/task.ipynb
run:
  - jupyter-execute "${relativeTaskPath}/task.ipynb"
  - cd "${relativeTaskPath}/dist"; python task.py
  - mv "${relativeTaskPath}/dist/.answer.json" "${relativeTaskPath}/.solution.json"
  - python .laborantum/utils/checker.py -t "${relativeTaskPath}"
  - rm "${relativeTaskPath}/.answer.json"
  - rm "${relativeTaskPath}/.solution.json"
