artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/994825380441460877/2aa8a1a6e9de40b0b358bc3a15d301cb/artifacts
end_time: 1784393514251
entry_point_name: ''
experiment_id: '994825380441460877'
lifecycle_stage: active
run_id: 2aa8a1a6e9de40b0b358bc3a15d301cb
run_name: one_layer_fcnn_test_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1784393507727
status: 3
tags: []
user_id: root
