artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/994825380441460877/f5555941498743aeb89dfb79efc1b463/artifacts
end_time: 1784396325372
entry_point_name: ''
experiment_id: '994825380441460877'
lifecycle_stage: active
run_id: f5555941498743aeb89dfb79efc1b463
run_name: word2vec_hsoftmax_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1784396324403
status: 3
tags: []
user_id: root
