artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/994825380441460877/23ce2250140a42778db6cc5b5b47ddc2/artifacts
end_time: 1784395194686
entry_point_name: ''
experiment_id: '994825380441460877'
lifecycle_stage: active
run_id: 23ce2250140a42778db6cc5b5b47ddc2
run_name: autoencoder_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1784395178297
status: 3
tags: []
user_id: root
