artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/994825380441460877/b4e85397bbcb4ef6ae88e1163781cdf2/artifacts
end_time: 1784394383046
entry_point_name: ''
experiment_id: '994825380441460877'
lifecycle_stage: active
run_id: b4e85397bbcb4ef6ae88e1163781cdf2
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1784394269871
status: 3
tags: []
user_id: root
