artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/994825380441460877/478d0a5db797485291bc2eca2576e711/artifacts
end_time: 1784393528861
entry_point_name: ''
experiment_id: '994825380441460877'
lifecycle_stage: active
run_id: 478d0a5db797485291bc2eca2576e711
run_name: three_layer_fcnn_test_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1784393521476
status: 3
tags: []
user_id: root
